services:

  mysql_db:
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django_app:
    depends_on:
      - mysql_db
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  redis:
    image: redis:7.2.5-alpine
    hostname: redis

  celery:
    build:
      context: .
    hostname: celery
    entrypoint: celery
    command: -A DjangoDelivery.celery.app worker -l info
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    hostname: celery-beat
    entrypoint: celery
    command: -A DjangoDelivery.celery.app beat -l info
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  flower:
    image: mher/flower:2.0
    entrypoint: celery
    command: --broker=redis://redis:6379/0 flower
    ports:
      - 5555:5555
    depends_on:
      - django_app
      - redis
      - celery-beat

volumes:
  mysql_data: