# Generated by Django 5.0.6 on 2024-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
