# Generated by Django 5.0.6 on 2024-06-13 14:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryService', '0004_package_delivery_cost_alter_package_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Cost of delivery in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
